export const data = [
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consectetur nisl metus, ac laoreet urna faucibus in. Vivamus in sapien suscipit, aliquam dolor id, sollicitudin purus. Phasellus eleifend, tortor nec elementum commodo, orci nunc pharetra ex, vehicula efficitur nisl odio at diam. Quisque sit amet augue purus. Sed vitae libero velit. Proin vestibulum vulputate quam mollis consectetur. Morbi vel quam nec lorem pretium blandit fringilla quis justo. Proin aliquam viverra dictum. Pellentesque id porttitor nulla.`,

  `Fusce sed aliquam nulla. Cras dignissim ultrices ex, ac dapibus mauris tincidunt consequat. Fusce nunc nisi, condimentum et ex nec, iaculis varius sapien. Mauris lectus lectus, commodo eget scelerisque vitae, placerat rhoncus felis. Phasellus eu nibh dui. Ut non mauris tempus, accumsan arcu quis, pretium lacus. Donec ut egestas elit. Nulla elementum erat id felis efficitur fermentum. Donec et aliquet leo.`,

  `Phasellus fermentum, ante quis malesuada luctus, lorem magna fermentum mauris, quis faucibus mauris elit in erat. Nulla facilisi. Nunc quis ultricies augue. Sed venenatis nisl at turpis bibendum vulputate. Cras felis ipsum, fringilla sit amet dui at, tristique ultrices dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sit amet ex lacus. Phasellus metus sapien, ornare at semper a, hendrerit ac purus.`,

  `Nam sed nunc pretium, suscipit massa id, tincidunt augue. Proin et eros iaculis, egestas urna eu, porta tellus. Aenean a rutrum metus. Duis eu est id mi tristique laoreet. Vestibulum laoreet tincidunt lectus. Morbi bibendum magna a nulla cursus, sit amet dapibus nibh semper. Donec faucibus enim dignissim, semper augue nec, fermentum tellus. Sed viverra pretium neque imperdiet lacinia. Cras dictum tempor felis, in lobortis tortor lacinia a.`,

  `Phasellus pulvinar iaculis arcu, eu ullamcorper lacus porta at. Morbi commodo urna nisi, in gravida orci iaculis eget. Duis velit odio, hendrerit vel velit nec, pulvinar congue dui. Aliquam erat volutpat. Vivamus auctor odio eget libero laoreet, sit amet egestas ligula finibus. Morbi condimentum dolor vel neque gravida ullamcorper. Nam vitae ullamcorper ipsum. Mauris eu gravida lacus. In vel fermentum sem. Nulla dignissim suscipit massa, a vehicula est placerat at. Nullam aliquam augue ut magna aliquam consequat. Nunc lacus mi, congue ut lacus ut, blandit fringilla quam. Vivamus vel ex erat. Aenean pulvinar ultrices risus. Aliquam auctor malesuada aliquam.`,

  `Nunc facilisis commodo sapien, id malesuada lorem aliquet ut. Cras ac nulla ac ligula venenatis porttitor vel ac felis. Nulla luctus luctus libero. Nam non eros lorem. Nunc molestie eros ut leo dictum rhoncus. Integer nec purus vitae nulla sodales scelerisque. Ut velit lacus, mattis in aliquam sit amet, ultrices ac dui. In non tortor ac nibh tristique eleifend a eu est. Maecenas arcu urna, pretium sit amet velit id, blandit aliquam urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget dignissim nibh. Donec semper lorem risus, at maximus mi sollicitudin quis. Proin vehicula nec mi at maximus. Praesent et mi ut arcu hendrerit facilisis. Sed arcu elit, commodo ut turpis eu, fringilla blandit justo.`,

  `Integer a enim lorem. Cras vel auctor mauris, at vehicula ipsum. Donec et cursus elit, sit amet vehicula lacus. Vivamus suscipit justo sapien, nec rutrum nulla volutpat id. Donec efficitur arcu sit amet ante interdum scelerisque. In fermentum eros metus, ut facilisis magna tristique nec. Quisque erat ex, aliquam vel mauris at, accumsan fringilla odio. Sed molestie tortor quam, nec consectetur nisi maximus ac. Vestibulum bibendum gravida neque, sed mattis lacus volutpat quis.`,
];
